package hello.data.model;

public class Testc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testc.ID
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testc.NAME
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testc.AGE
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testc.ID
     *
     * @return the value of testc.ID
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testc.ID
     *
     * @param id the value for testc.ID
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testc.NAME
     *
     * @return the value of testc.NAME
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testc.NAME
     *
     * @param name the value for testc.NAME
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testc.AGE
     *
     * @return the value of testc.AGE
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testc.AGE
     *
     * @param age the value for testc.AGE
     *
     * @mbggenerated Mon Jun 24 11:50:51 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}