package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.mapper;

import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.UcAreaDO;
import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.UcAreaDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UcAreaDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    long countByExample(UcAreaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int deleteByExample(UcAreaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int insert(UcAreaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int insertSelective(UcAreaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    List<UcAreaDO> selectByExample(UcAreaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    UcAreaDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") UcAreaDO record, @Param("example") UcAreaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int updateByExample(@Param("record") UcAreaDO record, @Param("example") UcAreaDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int updateByPrimaryKeySelective(UcAreaDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_area
     *
     * @mbg.generated Tue Apr 09 19:34:22 CST 2019
     */
    int updateByPrimaryKey(UcAreaDO record);
}