package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_custkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private Integer cCustkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_name
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_address
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_nationkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private Integer cNationkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_phone
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_acctbal
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private Double cAcctbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_mktsegment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private String cMktsegment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.c_comment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    private String cComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_custkey
     *
     * @return the value of customer.c_custkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public Integer getcCustkey() {
        return cCustkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_custkey
     *
     * @param cCustkey the value for customer.c_custkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcCustkey(Integer cCustkey) {
        this.cCustkey = cCustkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_name
     *
     * @return the value of customer.c_name
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_name
     *
     * @param cName the value for customer.c_name
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_address
     *
     * @return the value of customer.c_address
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_address
     *
     * @param cAddress the value for customer.c_address
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_nationkey
     *
     * @return the value of customer.c_nationkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public Integer getcNationkey() {
        return cNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_nationkey
     *
     * @param cNationkey the value for customer.c_nationkey
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcNationkey(Integer cNationkey) {
        this.cNationkey = cNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_phone
     *
     * @return the value of customer.c_phone
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_phone
     *
     * @param cPhone the value for customer.c_phone
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone == null ? null : cPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_acctbal
     *
     * @return the value of customer.c_acctbal
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public Double getcAcctbal() {
        return cAcctbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_acctbal
     *
     * @param cAcctbal the value for customer.c_acctbal
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcAcctbal(Double cAcctbal) {
        this.cAcctbal = cAcctbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_mktsegment
     *
     * @return the value of customer.c_mktsegment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getcMktsegment() {
        return cMktsegment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_mktsegment
     *
     * @param cMktsegment the value for customer.c_mktsegment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcMktsegment(String cMktsegment) {
        this.cMktsegment = cMktsegment == null ? null : cMktsegment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.c_comment
     *
     * @return the value of customer.c_comment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getcComment() {
        return cComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.c_comment
     *
     * @param cComment the value for customer.c_comment
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setcComment(String cComment) {
        this.cComment = cComment == null ? null : cComment.trim();
    }
}