package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCCustkeyIsNull() {
            addCriterion("c_custkey is null");
            return (Criteria) this;
        }

        public Criteria andCCustkeyIsNotNull() {
            addCriterion("c_custkey is not null");
            return (Criteria) this;
        }

        public Criteria andCCustkeyEqualTo(Integer value) {
            addCriterion("c_custkey =", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyNotEqualTo(Integer value) {
            addCriterion("c_custkey <>", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyGreaterThan(Integer value) {
            addCriterion("c_custkey >", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_custkey >=", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyLessThan(Integer value) {
            addCriterion("c_custkey <", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyLessThanOrEqualTo(Integer value) {
            addCriterion("c_custkey <=", value, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyIn(List<Integer> values) {
            addCriterion("c_custkey in", values, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyNotIn(List<Integer> values) {
            addCriterion("c_custkey not in", values, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyBetween(Integer value1, Integer value2) {
            addCriterion("c_custkey between", value1, value2, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCCustkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("c_custkey not between", value1, value2, "cCustkey");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCAddressIsNull() {
            addCriterion("c_address is null");
            return (Criteria) this;
        }

        public Criteria andCAddressIsNotNull() {
            addCriterion("c_address is not null");
            return (Criteria) this;
        }

        public Criteria andCAddressEqualTo(String value) {
            addCriterion("c_address =", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotEqualTo(String value) {
            addCriterion("c_address <>", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressGreaterThan(String value) {
            addCriterion("c_address >", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressGreaterThanOrEqualTo(String value) {
            addCriterion("c_address >=", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLessThan(String value) {
            addCriterion("c_address <", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLessThanOrEqualTo(String value) {
            addCriterion("c_address <=", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressLike(String value) {
            addCriterion("c_address like", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotLike(String value) {
            addCriterion("c_address not like", value, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressIn(List<String> values) {
            addCriterion("c_address in", values, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotIn(List<String> values) {
            addCriterion("c_address not in", values, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressBetween(String value1, String value2) {
            addCriterion("c_address between", value1, value2, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCAddressNotBetween(String value1, String value2) {
            addCriterion("c_address not between", value1, value2, "cAddress");
            return (Criteria) this;
        }

        public Criteria andCNationkeyIsNull() {
            addCriterion("c_nationkey is null");
            return (Criteria) this;
        }

        public Criteria andCNationkeyIsNotNull() {
            addCriterion("c_nationkey is not null");
            return (Criteria) this;
        }

        public Criteria andCNationkeyEqualTo(Integer value) {
            addCriterion("c_nationkey =", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyNotEqualTo(Integer value) {
            addCriterion("c_nationkey <>", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyGreaterThan(Integer value) {
            addCriterion("c_nationkey >", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_nationkey >=", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyLessThan(Integer value) {
            addCriterion("c_nationkey <", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyLessThanOrEqualTo(Integer value) {
            addCriterion("c_nationkey <=", value, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyIn(List<Integer> values) {
            addCriterion("c_nationkey in", values, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyNotIn(List<Integer> values) {
            addCriterion("c_nationkey not in", values, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyBetween(Integer value1, Integer value2) {
            addCriterion("c_nationkey between", value1, value2, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCNationkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("c_nationkey not between", value1, value2, "cNationkey");
            return (Criteria) this;
        }

        public Criteria andCPhoneIsNull() {
            addCriterion("c_phone is null");
            return (Criteria) this;
        }

        public Criteria andCPhoneIsNotNull() {
            addCriterion("c_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCPhoneEqualTo(String value) {
            addCriterion("c_phone =", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotEqualTo(String value) {
            addCriterion("c_phone <>", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneGreaterThan(String value) {
            addCriterion("c_phone >", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("c_phone >=", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLessThan(String value) {
            addCriterion("c_phone <", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLessThanOrEqualTo(String value) {
            addCriterion("c_phone <=", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneLike(String value) {
            addCriterion("c_phone like", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotLike(String value) {
            addCriterion("c_phone not like", value, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneIn(List<String> values) {
            addCriterion("c_phone in", values, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotIn(List<String> values) {
            addCriterion("c_phone not in", values, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneBetween(String value1, String value2) {
            addCriterion("c_phone between", value1, value2, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCPhoneNotBetween(String value1, String value2) {
            addCriterion("c_phone not between", value1, value2, "cPhone");
            return (Criteria) this;
        }

        public Criteria andCAcctbalIsNull() {
            addCriterion("c_acctbal is null");
            return (Criteria) this;
        }

        public Criteria andCAcctbalIsNotNull() {
            addCriterion("c_acctbal is not null");
            return (Criteria) this;
        }

        public Criteria andCAcctbalEqualTo(Double value) {
            addCriterion("c_acctbal =", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalNotEqualTo(Double value) {
            addCriterion("c_acctbal <>", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalGreaterThan(Double value) {
            addCriterion("c_acctbal >", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalGreaterThanOrEqualTo(Double value) {
            addCriterion("c_acctbal >=", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalLessThan(Double value) {
            addCriterion("c_acctbal <", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalLessThanOrEqualTo(Double value) {
            addCriterion("c_acctbal <=", value, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalIn(List<Double> values) {
            addCriterion("c_acctbal in", values, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalNotIn(List<Double> values) {
            addCriterion("c_acctbal not in", values, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalBetween(Double value1, Double value2) {
            addCriterion("c_acctbal between", value1, value2, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCAcctbalNotBetween(Double value1, Double value2) {
            addCriterion("c_acctbal not between", value1, value2, "cAcctbal");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentIsNull() {
            addCriterion("c_mktsegment is null");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentIsNotNull() {
            addCriterion("c_mktsegment is not null");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentEqualTo(String value) {
            addCriterion("c_mktsegment =", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentNotEqualTo(String value) {
            addCriterion("c_mktsegment <>", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentGreaterThan(String value) {
            addCriterion("c_mktsegment >", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentGreaterThanOrEqualTo(String value) {
            addCriterion("c_mktsegment >=", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentLessThan(String value) {
            addCriterion("c_mktsegment <", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentLessThanOrEqualTo(String value) {
            addCriterion("c_mktsegment <=", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentLike(String value) {
            addCriterion("c_mktsegment like", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentNotLike(String value) {
            addCriterion("c_mktsegment not like", value, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentIn(List<String> values) {
            addCriterion("c_mktsegment in", values, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentNotIn(List<String> values) {
            addCriterion("c_mktsegment not in", values, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentBetween(String value1, String value2) {
            addCriterion("c_mktsegment between", value1, value2, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCMktsegmentNotBetween(String value1, String value2) {
            addCriterion("c_mktsegment not between", value1, value2, "cMktsegment");
            return (Criteria) this;
        }

        public Criteria andCCommentIsNull() {
            addCriterion("c_comment is null");
            return (Criteria) this;
        }

        public Criteria andCCommentIsNotNull() {
            addCriterion("c_comment is not null");
            return (Criteria) this;
        }

        public Criteria andCCommentEqualTo(String value) {
            addCriterion("c_comment =", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentNotEqualTo(String value) {
            addCriterion("c_comment <>", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentGreaterThan(String value) {
            addCriterion("c_comment >", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentGreaterThanOrEqualTo(String value) {
            addCriterion("c_comment >=", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentLessThan(String value) {
            addCriterion("c_comment <", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentLessThanOrEqualTo(String value) {
            addCriterion("c_comment <=", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentLike(String value) {
            addCriterion("c_comment like", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentNotLike(String value) {
            addCriterion("c_comment not like", value, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentIn(List<String> values) {
            addCriterion("c_comment in", values, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentNotIn(List<String> values) {
            addCriterion("c_comment not in", values, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentBetween(String value1, String value2) {
            addCriterion("c_comment between", value1, value2, "cComment");
            return (Criteria) this;
        }

        public Criteria andCCommentNotBetween(String value1, String value2) {
            addCriterion("c_comment not between", value1, value2, "cComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:31:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer
     *
     * @mbggenerated Fri Jun 14 14:31:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}