package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class LineitemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public LineitemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andLOrderkeyIsNull() {
            addCriterion("l_orderkey is null");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyIsNotNull() {
            addCriterion("l_orderkey is not null");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyEqualTo(Integer value) {
            addCriterion("l_orderkey =", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyNotEqualTo(Integer value) {
            addCriterion("l_orderkey <>", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyGreaterThan(Integer value) {
            addCriterion("l_orderkey >", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("l_orderkey >=", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyLessThan(Integer value) {
            addCriterion("l_orderkey <", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyLessThanOrEqualTo(Integer value) {
            addCriterion("l_orderkey <=", value, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyIn(List<Integer> values) {
            addCriterion("l_orderkey in", values, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyNotIn(List<Integer> values) {
            addCriterion("l_orderkey not in", values, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyBetween(Integer value1, Integer value2) {
            addCriterion("l_orderkey between", value1, value2, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLOrderkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("l_orderkey not between", value1, value2, "lOrderkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyIsNull() {
            addCriterion("l_partkey is null");
            return (Criteria) this;
        }

        public Criteria andLPartkeyIsNotNull() {
            addCriterion("l_partkey is not null");
            return (Criteria) this;
        }

        public Criteria andLPartkeyEqualTo(Integer value) {
            addCriterion("l_partkey =", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyNotEqualTo(Integer value) {
            addCriterion("l_partkey <>", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyGreaterThan(Integer value) {
            addCriterion("l_partkey >", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("l_partkey >=", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyLessThan(Integer value) {
            addCriterion("l_partkey <", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyLessThanOrEqualTo(Integer value) {
            addCriterion("l_partkey <=", value, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyIn(List<Integer> values) {
            addCriterion("l_partkey in", values, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyNotIn(List<Integer> values) {
            addCriterion("l_partkey not in", values, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyBetween(Integer value1, Integer value2) {
            addCriterion("l_partkey between", value1, value2, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLPartkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("l_partkey not between", value1, value2, "lPartkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyIsNull() {
            addCriterion("l_suppkey is null");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyIsNotNull() {
            addCriterion("l_suppkey is not null");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyEqualTo(Integer value) {
            addCriterion("l_suppkey =", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyNotEqualTo(Integer value) {
            addCriterion("l_suppkey <>", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyGreaterThan(Integer value) {
            addCriterion("l_suppkey >", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("l_suppkey >=", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyLessThan(Integer value) {
            addCriterion("l_suppkey <", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyLessThanOrEqualTo(Integer value) {
            addCriterion("l_suppkey <=", value, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyIn(List<Integer> values) {
            addCriterion("l_suppkey in", values, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyNotIn(List<Integer> values) {
            addCriterion("l_suppkey not in", values, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyBetween(Integer value1, Integer value2) {
            addCriterion("l_suppkey between", value1, value2, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLSuppkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("l_suppkey not between", value1, value2, "lSuppkey");
            return (Criteria) this;
        }

        public Criteria andLLinenumberIsNull() {
            addCriterion("l_linenumber is null");
            return (Criteria) this;
        }

        public Criteria andLLinenumberIsNotNull() {
            addCriterion("l_linenumber is not null");
            return (Criteria) this;
        }

        public Criteria andLLinenumberEqualTo(Integer value) {
            addCriterion("l_linenumber =", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberNotEqualTo(Integer value) {
            addCriterion("l_linenumber <>", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberGreaterThan(Integer value) {
            addCriterion("l_linenumber >", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("l_linenumber >=", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberLessThan(Integer value) {
            addCriterion("l_linenumber <", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberLessThanOrEqualTo(Integer value) {
            addCriterion("l_linenumber <=", value, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberIn(List<Integer> values) {
            addCriterion("l_linenumber in", values, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberNotIn(List<Integer> values) {
            addCriterion("l_linenumber not in", values, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberBetween(Integer value1, Integer value2) {
            addCriterion("l_linenumber between", value1, value2, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLLinenumberNotBetween(Integer value1, Integer value2) {
            addCriterion("l_linenumber not between", value1, value2, "lLinenumber");
            return (Criteria) this;
        }

        public Criteria andLQuantityIsNull() {
            addCriterion("l_quantity is null");
            return (Criteria) this;
        }

        public Criteria andLQuantityIsNotNull() {
            addCriterion("l_quantity is not null");
            return (Criteria) this;
        }

        public Criteria andLQuantityEqualTo(Double value) {
            addCriterion("l_quantity =", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityNotEqualTo(Double value) {
            addCriterion("l_quantity <>", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityGreaterThan(Double value) {
            addCriterion("l_quantity >", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("l_quantity >=", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityLessThan(Double value) {
            addCriterion("l_quantity <", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityLessThanOrEqualTo(Double value) {
            addCriterion("l_quantity <=", value, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityIn(List<Double> values) {
            addCriterion("l_quantity in", values, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityNotIn(List<Double> values) {
            addCriterion("l_quantity not in", values, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityBetween(Double value1, Double value2) {
            addCriterion("l_quantity between", value1, value2, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLQuantityNotBetween(Double value1, Double value2) {
            addCriterion("l_quantity not between", value1, value2, "lQuantity");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceIsNull() {
            addCriterion("l_extendedprice is null");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceIsNotNull() {
            addCriterion("l_extendedprice is not null");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceEqualTo(Double value) {
            addCriterion("l_extendedprice =", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceNotEqualTo(Double value) {
            addCriterion("l_extendedprice <>", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceGreaterThan(Double value) {
            addCriterion("l_extendedprice >", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("l_extendedprice >=", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceLessThan(Double value) {
            addCriterion("l_extendedprice <", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceLessThanOrEqualTo(Double value) {
            addCriterion("l_extendedprice <=", value, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceIn(List<Double> values) {
            addCriterion("l_extendedprice in", values, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceNotIn(List<Double> values) {
            addCriterion("l_extendedprice not in", values, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceBetween(Double value1, Double value2) {
            addCriterion("l_extendedprice between", value1, value2, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLExtendedpriceNotBetween(Double value1, Double value2) {
            addCriterion("l_extendedprice not between", value1, value2, "lExtendedprice");
            return (Criteria) this;
        }

        public Criteria andLDiscountIsNull() {
            addCriterion("l_discount is null");
            return (Criteria) this;
        }

        public Criteria andLDiscountIsNotNull() {
            addCriterion("l_discount is not null");
            return (Criteria) this;
        }

        public Criteria andLDiscountEqualTo(Double value) {
            addCriterion("l_discount =", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountNotEqualTo(Double value) {
            addCriterion("l_discount <>", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountGreaterThan(Double value) {
            addCriterion("l_discount >", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountGreaterThanOrEqualTo(Double value) {
            addCriterion("l_discount >=", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountLessThan(Double value) {
            addCriterion("l_discount <", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountLessThanOrEqualTo(Double value) {
            addCriterion("l_discount <=", value, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountIn(List<Double> values) {
            addCriterion("l_discount in", values, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountNotIn(List<Double> values) {
            addCriterion("l_discount not in", values, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountBetween(Double value1, Double value2) {
            addCriterion("l_discount between", value1, value2, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLDiscountNotBetween(Double value1, Double value2) {
            addCriterion("l_discount not between", value1, value2, "lDiscount");
            return (Criteria) this;
        }

        public Criteria andLTaxIsNull() {
            addCriterion("l_tax is null");
            return (Criteria) this;
        }

        public Criteria andLTaxIsNotNull() {
            addCriterion("l_tax is not null");
            return (Criteria) this;
        }

        public Criteria andLTaxEqualTo(Double value) {
            addCriterion("l_tax =", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxNotEqualTo(Double value) {
            addCriterion("l_tax <>", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxGreaterThan(Double value) {
            addCriterion("l_tax >", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxGreaterThanOrEqualTo(Double value) {
            addCriterion("l_tax >=", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxLessThan(Double value) {
            addCriterion("l_tax <", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxLessThanOrEqualTo(Double value) {
            addCriterion("l_tax <=", value, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxIn(List<Double> values) {
            addCriterion("l_tax in", values, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxNotIn(List<Double> values) {
            addCriterion("l_tax not in", values, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxBetween(Double value1, Double value2) {
            addCriterion("l_tax between", value1, value2, "lTax");
            return (Criteria) this;
        }

        public Criteria andLTaxNotBetween(Double value1, Double value2) {
            addCriterion("l_tax not between", value1, value2, "lTax");
            return (Criteria) this;
        }

        public Criteria andLReturnflagIsNull() {
            addCriterion("l_returnflag is null");
            return (Criteria) this;
        }

        public Criteria andLReturnflagIsNotNull() {
            addCriterion("l_returnflag is not null");
            return (Criteria) this;
        }

        public Criteria andLReturnflagEqualTo(String value) {
            addCriterion("l_returnflag =", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagNotEqualTo(String value) {
            addCriterion("l_returnflag <>", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagGreaterThan(String value) {
            addCriterion("l_returnflag >", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagGreaterThanOrEqualTo(String value) {
            addCriterion("l_returnflag >=", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagLessThan(String value) {
            addCriterion("l_returnflag <", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagLessThanOrEqualTo(String value) {
            addCriterion("l_returnflag <=", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagLike(String value) {
            addCriterion("l_returnflag like", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagNotLike(String value) {
            addCriterion("l_returnflag not like", value, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagIn(List<String> values) {
            addCriterion("l_returnflag in", values, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagNotIn(List<String> values) {
            addCriterion("l_returnflag not in", values, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagBetween(String value1, String value2) {
            addCriterion("l_returnflag between", value1, value2, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLReturnflagNotBetween(String value1, String value2) {
            addCriterion("l_returnflag not between", value1, value2, "lReturnflag");
            return (Criteria) this;
        }

        public Criteria andLLinestatusIsNull() {
            addCriterion("l_linestatus is null");
            return (Criteria) this;
        }

        public Criteria andLLinestatusIsNotNull() {
            addCriterion("l_linestatus is not null");
            return (Criteria) this;
        }

        public Criteria andLLinestatusEqualTo(String value) {
            addCriterion("l_linestatus =", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusNotEqualTo(String value) {
            addCriterion("l_linestatus <>", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusGreaterThan(String value) {
            addCriterion("l_linestatus >", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusGreaterThanOrEqualTo(String value) {
            addCriterion("l_linestatus >=", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusLessThan(String value) {
            addCriterion("l_linestatus <", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusLessThanOrEqualTo(String value) {
            addCriterion("l_linestatus <=", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusLike(String value) {
            addCriterion("l_linestatus like", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusNotLike(String value) {
            addCriterion("l_linestatus not like", value, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusIn(List<String> values) {
            addCriterion("l_linestatus in", values, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusNotIn(List<String> values) {
            addCriterion("l_linestatus not in", values, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusBetween(String value1, String value2) {
            addCriterion("l_linestatus between", value1, value2, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLLinestatusNotBetween(String value1, String value2) {
            addCriterion("l_linestatus not between", value1, value2, "lLinestatus");
            return (Criteria) this;
        }

        public Criteria andLShipdateIsNull() {
            addCriterion("l_shipDATE is null");
            return (Criteria) this;
        }

        public Criteria andLShipdateIsNotNull() {
            addCriterion("l_shipDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLShipdateEqualTo(Date value) {
            addCriterionForJDBCDate("l_shipDATE =", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("l_shipDATE <>", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateGreaterThan(Date value) {
            addCriterionForJDBCDate("l_shipDATE >", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_shipDATE >=", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateLessThan(Date value) {
            addCriterionForJDBCDate("l_shipDATE <", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_shipDATE <=", value, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateIn(List<Date> values) {
            addCriterionForJDBCDate("l_shipDATE in", values, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("l_shipDATE not in", values, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_shipDATE between", value1, value2, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLShipdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_shipDATE not between", value1, value2, "lShipdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateIsNull() {
            addCriterion("l_commitDATE is null");
            return (Criteria) this;
        }

        public Criteria andLCommitdateIsNotNull() {
            addCriterion("l_commitDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLCommitdateEqualTo(Date value) {
            addCriterionForJDBCDate("l_commitDATE =", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("l_commitDATE <>", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateGreaterThan(Date value) {
            addCriterionForJDBCDate("l_commitDATE >", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_commitDATE >=", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateLessThan(Date value) {
            addCriterionForJDBCDate("l_commitDATE <", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_commitDATE <=", value, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateIn(List<Date> values) {
            addCriterionForJDBCDate("l_commitDATE in", values, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("l_commitDATE not in", values, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_commitDATE between", value1, value2, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLCommitdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_commitDATE not between", value1, value2, "lCommitdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateIsNull() {
            addCriterion("l_receiptDATE is null");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateIsNotNull() {
            addCriterion("l_receiptDATE is not null");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateEqualTo(Date value) {
            addCriterionForJDBCDate("l_receiptDATE =", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("l_receiptDATE <>", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateGreaterThan(Date value) {
            addCriterionForJDBCDate("l_receiptDATE >", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_receiptDATE >=", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateLessThan(Date value) {
            addCriterionForJDBCDate("l_receiptDATE <", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("l_receiptDATE <=", value, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateIn(List<Date> values) {
            addCriterionForJDBCDate("l_receiptDATE in", values, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("l_receiptDATE not in", values, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_receiptDATE between", value1, value2, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLReceiptdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("l_receiptDATE not between", value1, value2, "lReceiptdate");
            return (Criteria) this;
        }

        public Criteria andLShipinstructIsNull() {
            addCriterion("l_shipinstruct is null");
            return (Criteria) this;
        }

        public Criteria andLShipinstructIsNotNull() {
            addCriterion("l_shipinstruct is not null");
            return (Criteria) this;
        }

        public Criteria andLShipinstructEqualTo(String value) {
            addCriterion("l_shipinstruct =", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructNotEqualTo(String value) {
            addCriterion("l_shipinstruct <>", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructGreaterThan(String value) {
            addCriterion("l_shipinstruct >", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructGreaterThanOrEqualTo(String value) {
            addCriterion("l_shipinstruct >=", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructLessThan(String value) {
            addCriterion("l_shipinstruct <", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructLessThanOrEqualTo(String value) {
            addCriterion("l_shipinstruct <=", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructLike(String value) {
            addCriterion("l_shipinstruct like", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructNotLike(String value) {
            addCriterion("l_shipinstruct not like", value, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructIn(List<String> values) {
            addCriterion("l_shipinstruct in", values, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructNotIn(List<String> values) {
            addCriterion("l_shipinstruct not in", values, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructBetween(String value1, String value2) {
            addCriterion("l_shipinstruct between", value1, value2, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipinstructNotBetween(String value1, String value2) {
            addCriterion("l_shipinstruct not between", value1, value2, "lShipinstruct");
            return (Criteria) this;
        }

        public Criteria andLShipmodeIsNull() {
            addCriterion("l_shipmode is null");
            return (Criteria) this;
        }

        public Criteria andLShipmodeIsNotNull() {
            addCriterion("l_shipmode is not null");
            return (Criteria) this;
        }

        public Criteria andLShipmodeEqualTo(String value) {
            addCriterion("l_shipmode =", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeNotEqualTo(String value) {
            addCriterion("l_shipmode <>", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeGreaterThan(String value) {
            addCriterion("l_shipmode >", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeGreaterThanOrEqualTo(String value) {
            addCriterion("l_shipmode >=", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeLessThan(String value) {
            addCriterion("l_shipmode <", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeLessThanOrEqualTo(String value) {
            addCriterion("l_shipmode <=", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeLike(String value) {
            addCriterion("l_shipmode like", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeNotLike(String value) {
            addCriterion("l_shipmode not like", value, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeIn(List<String> values) {
            addCriterion("l_shipmode in", values, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeNotIn(List<String> values) {
            addCriterion("l_shipmode not in", values, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeBetween(String value1, String value2) {
            addCriterion("l_shipmode between", value1, value2, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLShipmodeNotBetween(String value1, String value2) {
            addCriterion("l_shipmode not between", value1, value2, "lShipmode");
            return (Criteria) this;
        }

        public Criteria andLCommentIsNull() {
            addCriterion("l_comment is null");
            return (Criteria) this;
        }

        public Criteria andLCommentIsNotNull() {
            addCriterion("l_comment is not null");
            return (Criteria) this;
        }

        public Criteria andLCommentEqualTo(String value) {
            addCriterion("l_comment =", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentNotEqualTo(String value) {
            addCriterion("l_comment <>", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentGreaterThan(String value) {
            addCriterion("l_comment >", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentGreaterThanOrEqualTo(String value) {
            addCriterion("l_comment >=", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentLessThan(String value) {
            addCriterion("l_comment <", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentLessThanOrEqualTo(String value) {
            addCriterion("l_comment <=", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentLike(String value) {
            addCriterion("l_comment like", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentNotLike(String value) {
            addCriterion("l_comment not like", value, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentIn(List<String> values) {
            addCriterion("l_comment in", values, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentNotIn(List<String> values) {
            addCriterion("l_comment not in", values, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentBetween(String value1, String value2) {
            addCriterion("l_comment between", value1, value2, "lComment");
            return (Criteria) this;
        }

        public Criteria andLCommentNotBetween(String value1, String value2) {
            addCriterion("l_comment not between", value1, value2, "lComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lineitem
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:32:46 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}