package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class NationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public NationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNNationkeyIsNull() {
            addCriterion("n_nationkey is null");
            return (Criteria) this;
        }

        public Criteria andNNationkeyIsNotNull() {
            addCriterion("n_nationkey is not null");
            return (Criteria) this;
        }

        public Criteria andNNationkeyEqualTo(Integer value) {
            addCriterion("n_nationkey =", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyNotEqualTo(Integer value) {
            addCriterion("n_nationkey <>", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyGreaterThan(Integer value) {
            addCriterion("n_nationkey >", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_nationkey >=", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyLessThan(Integer value) {
            addCriterion("n_nationkey <", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyLessThanOrEqualTo(Integer value) {
            addCriterion("n_nationkey <=", value, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyIn(List<Integer> values) {
            addCriterion("n_nationkey in", values, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyNotIn(List<Integer> values) {
            addCriterion("n_nationkey not in", values, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyBetween(Integer value1, Integer value2) {
            addCriterion("n_nationkey between", value1, value2, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNationkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("n_nationkey not between", value1, value2, "nNationkey");
            return (Criteria) this;
        }

        public Criteria andNNameIsNull() {
            addCriterion("n_name is null");
            return (Criteria) this;
        }

        public Criteria andNNameIsNotNull() {
            addCriterion("n_name is not null");
            return (Criteria) this;
        }

        public Criteria andNNameEqualTo(String value) {
            addCriterion("n_name =", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameNotEqualTo(String value) {
            addCriterion("n_name <>", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameGreaterThan(String value) {
            addCriterion("n_name >", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameGreaterThanOrEqualTo(String value) {
            addCriterion("n_name >=", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameLessThan(String value) {
            addCriterion("n_name <", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameLessThanOrEqualTo(String value) {
            addCriterion("n_name <=", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameLike(String value) {
            addCriterion("n_name like", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameNotLike(String value) {
            addCriterion("n_name not like", value, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameIn(List<String> values) {
            addCriterion("n_name in", values, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameNotIn(List<String> values) {
            addCriterion("n_name not in", values, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameBetween(String value1, String value2) {
            addCriterion("n_name between", value1, value2, "nName");
            return (Criteria) this;
        }

        public Criteria andNNameNotBetween(String value1, String value2) {
            addCriterion("n_name not between", value1, value2, "nName");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyIsNull() {
            addCriterion("n_regionkey is null");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyIsNotNull() {
            addCriterion("n_regionkey is not null");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyEqualTo(Integer value) {
            addCriterion("n_regionkey =", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyNotEqualTo(Integer value) {
            addCriterion("n_regionkey <>", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyGreaterThan(Integer value) {
            addCriterion("n_regionkey >", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("n_regionkey >=", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyLessThan(Integer value) {
            addCriterion("n_regionkey <", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyLessThanOrEqualTo(Integer value) {
            addCriterion("n_regionkey <=", value, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyIn(List<Integer> values) {
            addCriterion("n_regionkey in", values, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyNotIn(List<Integer> values) {
            addCriterion("n_regionkey not in", values, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyBetween(Integer value1, Integer value2) {
            addCriterion("n_regionkey between", value1, value2, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNRegionkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("n_regionkey not between", value1, value2, "nRegionkey");
            return (Criteria) this;
        }

        public Criteria andNCommentIsNull() {
            addCriterion("n_comment is null");
            return (Criteria) this;
        }

        public Criteria andNCommentIsNotNull() {
            addCriterion("n_comment is not null");
            return (Criteria) this;
        }

        public Criteria andNCommentEqualTo(String value) {
            addCriterion("n_comment =", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentNotEqualTo(String value) {
            addCriterion("n_comment <>", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentGreaterThan(String value) {
            addCriterion("n_comment >", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentGreaterThanOrEqualTo(String value) {
            addCriterion("n_comment >=", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentLessThan(String value) {
            addCriterion("n_comment <", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentLessThanOrEqualTo(String value) {
            addCriterion("n_comment <=", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentLike(String value) {
            addCriterion("n_comment like", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentNotLike(String value) {
            addCriterion("n_comment not like", value, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentIn(List<String> values) {
            addCriterion("n_comment in", values, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentNotIn(List<String> values) {
            addCriterion("n_comment not in", values, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentBetween(String value1, String value2) {
            addCriterion("n_comment between", value1, value2, "nComment");
            return (Criteria) this;
        }

        public Criteria andNCommentNotBetween(String value1, String value2) {
            addCriterion("n_comment not between", value1, value2, "nComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nation
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:33:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nation
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}