package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class PartsuppExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public PartsuppExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPsPartkeyIsNull() {
            addCriterion("ps_partkey is null");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyIsNotNull() {
            addCriterion("ps_partkey is not null");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyEqualTo(Integer value) {
            addCriterion("ps_partkey =", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyNotEqualTo(Integer value) {
            addCriterion("ps_partkey <>", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyGreaterThan(Integer value) {
            addCriterion("ps_partkey >", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("ps_partkey >=", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyLessThan(Integer value) {
            addCriterion("ps_partkey <", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyLessThanOrEqualTo(Integer value) {
            addCriterion("ps_partkey <=", value, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyIn(List<Integer> values) {
            addCriterion("ps_partkey in", values, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyNotIn(List<Integer> values) {
            addCriterion("ps_partkey not in", values, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyBetween(Integer value1, Integer value2) {
            addCriterion("ps_partkey between", value1, value2, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsPartkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("ps_partkey not between", value1, value2, "psPartkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyIsNull() {
            addCriterion("ps_suppkey is null");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyIsNotNull() {
            addCriterion("ps_suppkey is not null");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyEqualTo(Integer value) {
            addCriterion("ps_suppkey =", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyNotEqualTo(Integer value) {
            addCriterion("ps_suppkey <>", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyGreaterThan(Integer value) {
            addCriterion("ps_suppkey >", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("ps_suppkey >=", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyLessThan(Integer value) {
            addCriterion("ps_suppkey <", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyLessThanOrEqualTo(Integer value) {
            addCriterion("ps_suppkey <=", value, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyIn(List<Integer> values) {
            addCriterion("ps_suppkey in", values, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyNotIn(List<Integer> values) {
            addCriterion("ps_suppkey not in", values, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyBetween(Integer value1, Integer value2) {
            addCriterion("ps_suppkey between", value1, value2, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsSuppkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("ps_suppkey not between", value1, value2, "psSuppkey");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyIsNull() {
            addCriterion("ps_availqty is null");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyIsNotNull() {
            addCriterion("ps_availqty is not null");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyEqualTo(Integer value) {
            addCriterion("ps_availqty =", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyNotEqualTo(Integer value) {
            addCriterion("ps_availqty <>", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyGreaterThan(Integer value) {
            addCriterion("ps_availqty >", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("ps_availqty >=", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyLessThan(Integer value) {
            addCriterion("ps_availqty <", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyLessThanOrEqualTo(Integer value) {
            addCriterion("ps_availqty <=", value, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyIn(List<Integer> values) {
            addCriterion("ps_availqty in", values, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyNotIn(List<Integer> values) {
            addCriterion("ps_availqty not in", values, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyBetween(Integer value1, Integer value2) {
            addCriterion("ps_availqty between", value1, value2, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsAvailqtyNotBetween(Integer value1, Integer value2) {
            addCriterion("ps_availqty not between", value1, value2, "psAvailqty");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostIsNull() {
            addCriterion("ps_supplycost is null");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostIsNotNull() {
            addCriterion("ps_supplycost is not null");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostEqualTo(Double value) {
            addCriterion("ps_supplycost =", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostNotEqualTo(Double value) {
            addCriterion("ps_supplycost <>", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostGreaterThan(Double value) {
            addCriterion("ps_supplycost >", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostGreaterThanOrEqualTo(Double value) {
            addCriterion("ps_supplycost >=", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostLessThan(Double value) {
            addCriterion("ps_supplycost <", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostLessThanOrEqualTo(Double value) {
            addCriterion("ps_supplycost <=", value, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostIn(List<Double> values) {
            addCriterion("ps_supplycost in", values, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostNotIn(List<Double> values) {
            addCriterion("ps_supplycost not in", values, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostBetween(Double value1, Double value2) {
            addCriterion("ps_supplycost between", value1, value2, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsSupplycostNotBetween(Double value1, Double value2) {
            addCriterion("ps_supplycost not between", value1, value2, "psSupplycost");
            return (Criteria) this;
        }

        public Criteria andPsCommentIsNull() {
            addCriterion("ps_comment is null");
            return (Criteria) this;
        }

        public Criteria andPsCommentIsNotNull() {
            addCriterion("ps_comment is not null");
            return (Criteria) this;
        }

        public Criteria andPsCommentEqualTo(String value) {
            addCriterion("ps_comment =", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentNotEqualTo(String value) {
            addCriterion("ps_comment <>", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentGreaterThan(String value) {
            addCriterion("ps_comment >", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentGreaterThanOrEqualTo(String value) {
            addCriterion("ps_comment >=", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentLessThan(String value) {
            addCriterion("ps_comment <", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentLessThanOrEqualTo(String value) {
            addCriterion("ps_comment <=", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentLike(String value) {
            addCriterion("ps_comment like", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentNotLike(String value) {
            addCriterion("ps_comment not like", value, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentIn(List<String> values) {
            addCriterion("ps_comment in", values, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentNotIn(List<String> values) {
            addCriterion("ps_comment not in", values, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentBetween(String value1, String value2) {
            addCriterion("ps_comment between", value1, value2, "psComment");
            return (Criteria) this;
        }

        public Criteria andPsCommentNotBetween(String value1, String value2) {
            addCriterion("ps_comment not between", value1, value2, "psComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partsupp
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:34:05 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}