package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private Integer sSuppkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_name
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private String sName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_address
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private String sAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_nationkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private Integer sNationkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_phone
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private String sPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_acctbal
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private Double sAcctbal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.s_comment
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    private String sComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_suppkey
     *
     * @return the value of supplier.s_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public Integer getsSuppkey() {
        return sSuppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_suppkey
     *
     * @param sSuppkey the value for supplier.s_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsSuppkey(Integer sSuppkey) {
        this.sSuppkey = sSuppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_name
     *
     * @return the value of supplier.s_name
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public String getsName() {
        return sName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_name
     *
     * @param sName the value for supplier.s_name
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsName(String sName) {
        this.sName = sName == null ? null : sName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_address
     *
     * @return the value of supplier.s_address
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public String getsAddress() {
        return sAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_address
     *
     * @param sAddress the value for supplier.s_address
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsAddress(String sAddress) {
        this.sAddress = sAddress == null ? null : sAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_nationkey
     *
     * @return the value of supplier.s_nationkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public Integer getsNationkey() {
        return sNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_nationkey
     *
     * @param sNationkey the value for supplier.s_nationkey
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsNationkey(Integer sNationkey) {
        this.sNationkey = sNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_phone
     *
     * @return the value of supplier.s_phone
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public String getsPhone() {
        return sPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_phone
     *
     * @param sPhone the value for supplier.s_phone
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsPhone(String sPhone) {
        this.sPhone = sPhone == null ? null : sPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_acctbal
     *
     * @return the value of supplier.s_acctbal
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public Double getsAcctbal() {
        return sAcctbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_acctbal
     *
     * @param sAcctbal the value for supplier.s_acctbal
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsAcctbal(Double sAcctbal) {
        this.sAcctbal = sAcctbal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.s_comment
     *
     * @return the value of supplier.s_comment
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public String getsComment() {
        return sComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.s_comment
     *
     * @param sComment the value for supplier.s_comment
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setsComment(String sComment) {
        this.sComment = sComment == null ? null : sComment.trim();
    }
}