server:
  port: 8091

spring:
  application:
    name: spring-cloud-client02
  zipkin:
    base-url: http://localhost:18093
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:18090/eureka,http://localhost:18091/eureka
