package com.demo.common.service.mysql.dal.model;

import java.util.Date;

public class Lineitem {
    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_orderkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Integer lOrderkey;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_partkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Integer lPartkey;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_suppkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Integer lSuppkey;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_linenumber
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Integer lLinenumber;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_quantity
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Double lQuantity;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_extendedprice
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Double lExtendedprice;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_discount
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Double lDiscount;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_tax
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Double lTax;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_returnflag
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private String lReturnflag;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_linestatus
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private String lLinestatus;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_shipDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Date lShipdate;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_commitDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Date lCommitdate;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_receiptDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private Date lReceiptdate;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_shipinstruct
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private String lShipinstruct;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_shipmode
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private String lShipmode;

    /**
     * This field was generated by my.batis Generator.
     * This field corresponds to the database column lineitem.l_comment
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    private String lComment;

    /**
     * This method was generated by my.batis Generator.
     * This method returns the value of the database column lineitem.l_orderkey
     *
     * @return the value of lineitem.l_orderkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Integer getlOrderkey() {
        return lOrderkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method sets the value of the database column lineitem.l_orderkey
     *
     * @param lOrderkey the value for lineitem.l_orderkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlOrderkey(Integer lOrderkey) {
        this.lOrderkey = lOrderkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method returns the value of the database column lineitem.l_partkey
     *
     * @return the value of lineitem.l_partkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Integer getlPartkey() {
        return lPartkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method sets the value of the database column lineitem.l_partkey
     *
     * @param lPartkey the value for lineitem.l_partkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlPartkey(Integer lPartkey) {
        this.lPartkey = lPartkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method returns the value of the database column lineitem.l_suppkey
     *
     * @return the value of lineitem.l_suppkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Integer getlSuppkey() {
        return lSuppkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method sets the value of the database column lineitem.l_suppkey
     *
     * @param lSuppkey the value for lineitem.l_suppkey
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlSuppkey(Integer lSuppkey) {
        this.lSuppkey = lSuppkey;
    }

    /**
     * This method was generated by my.batis Generator.
     * This method returns the value of the database column lineitem.l_linenumber
     *
     * @return the value of lineitem.l_linenumber
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Integer getlLinenumber() {
        return lLinenumber;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_linenumber
     *
     * @param lLinenumber the value for lineitem.l_linenumber
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlLinenumber(Integer lLinenumber) {
        this.lLinenumber = lLinenumber;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_quantity
     *
     * @return the value of lineitem.l_quantity
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Double getlQuantity() {
        return lQuantity;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_quantity
     *
     * @param lQuantity the value for lineitem.l_quantity
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlQuantity(Double lQuantity) {
        this.lQuantity = lQuantity;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_extendedprice
     *
     * @return the value of lineitem.l_extendedprice
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Double getlExtendedprice() {
        return lExtendedprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_extendedprice
     *
     * @param lExtendedprice the value for lineitem.l_extendedprice
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlExtendedprice(Double lExtendedprice) {
        this.lExtendedprice = lExtendedprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_discount
     *
     * @return the value of lineitem.l_discount
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Double getlDiscount() {
        return lDiscount;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_discount
     *
     * @param lDiscount the value for lineitem.l_discount
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlDiscount(Double lDiscount) {
        this.lDiscount = lDiscount;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_tax
     *
     * @return the value of lineitem.l_tax
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Double getlTax() {
        return lTax;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_tax
     *
     * @param lTax the value for lineitem.l_tax
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlTax(Double lTax) {
        this.lTax = lTax;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_returnflag
     *
     * @return the value of lineitem.l_returnflag
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getlReturnflag() {
        return lReturnflag;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_returnflag
     *
     * @param lReturnflag the value for lineitem.l_returnflag
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlReturnflag(String lReturnflag) {
        this.lReturnflag = lReturnflag == null ? null : lReturnflag.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_linestatus
     *
     * @return the value of lineitem.l_linestatus
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getlLinestatus() {
        return lLinestatus;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_linestatus
     *
     * @param lLinestatus the value for lineitem.l_linestatus
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlLinestatus(String lLinestatus) {
        this.lLinestatus = lLinestatus == null ? null : lLinestatus.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_shipDATE
     *
     * @return the value of lineitem.l_shipDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Date getlShipdate() {
        return lShipdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_shipDATE
     *
     * @param lShipdate the value for lineitem.l_shipDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlShipdate(Date lShipdate) {
        this.lShipdate = lShipdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_commitDATE
     *
     * @return the value of lineitem.l_commitDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Date getlCommitdate() {
        return lCommitdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_commitDATE
     *
     * @param lCommitdate the value for lineitem.l_commitDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlCommitdate(Date lCommitdate) {
        this.lCommitdate = lCommitdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_receiptDATE
     *
     * @return the value of lineitem.l_receiptDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public Date getlReceiptdate() {
        return lReceiptdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_receiptDATE
     *
     * @param lReceiptdate the value for lineitem.l_receiptDATE
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlReceiptdate(Date lReceiptdate) {
        this.lReceiptdate = lReceiptdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_shipinstruct
     *
     * @return the value of lineitem.l_shipinstruct
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getlShipinstruct() {
        return lShipinstruct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_shipinstruct
     *
     * @param lShipinstruct the value for lineitem.l_shipinstruct
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlShipinstruct(String lShipinstruct) {
        this.lShipinstruct = lShipinstruct == null ? null : lShipinstruct.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_shipmode
     *
     * @return the value of lineitem.l_shipmode
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getlShipmode() {
        return lShipmode;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_shipmode
     *
     * @param lShipmode the value for lineitem.l_shipmode
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlShipmode(String lShipmode) {
        this.lShipmode = lShipmode == null ? null : lShipmode.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column lineitem.l_comment
     *
     * @return the value of lineitem.l_comment
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public String getlComment() {
        return lComment;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column lineitem.l_comment
     *
     * @param lComment the value for lineitem.l_comment
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    public void setlComment(String lComment) {
        this.lComment = lComment == null ? null : lComment.trim();
    }
}