package com.demo.common.service.mysql.dal.model;

public class Nation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.n_nationkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    private Integer nNationkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.n_name
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    private String nName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.n_regionkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    private Integer nRegionkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.n_comment
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    private String nComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.n_nationkey
     *
     * @return the value of nation.n_nationkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public Integer getnNationkey() {
        return nNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.n_nationkey
     *
     * @param nNationkey the value for nation.n_nationkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setnNationkey(Integer nNationkey) {
        this.nNationkey = nNationkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.n_name
     *
     * @return the value of nation.n_name
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public String getnName() {
        return nName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.n_name
     *
     * @param nName the value for nation.n_name
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setnName(String nName) {
        this.nName = nName == null ? null : nName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.n_regionkey
     *
     * @return the value of nation.n_regionkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public Integer getnRegionkey() {
        return nRegionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.n_regionkey
     *
     * @param nRegionkey the value for nation.n_regionkey
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setnRegionkey(Integer nRegionkey) {
        this.nRegionkey = nRegionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.n_comment
     *
     * @return the value of nation.n_comment
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public String getnComment() {
        return nComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.n_comment
     *
     * @param nComment the value for nation.n_comment
     *
     * @mbggenerated Fri Jun 14 14:33:10 CST 2019
     */
    public void setnComment(String nComment) {
        this.nComment = nComment == null ? null : nComment.trim();
    }
}