package com.demo.common.service.mysql.dal.model;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_orderkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private Integer oOrderkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_custkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private Integer oCustkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_orderstatus
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private String oOrderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_totalprice
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private Double oTotalprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_orderDATE
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private Date oOrderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_orderpriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private String oOrderpriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_clerk
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private String oClerk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_shippriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private Integer oShippriority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.o_comment
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    private String oComment;

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_orderkey
     *
     * @return the value of orders.o_orderkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Integer getoOrderkey() {
        return oOrderkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_orderkey
     *
     * @param oOrderkey the value for orders.o_orderkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoOrderkey(Integer oOrderkey) {
        this.oOrderkey = oOrderkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_custkey
     *
     * @return the value of orders.o_custkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Integer getoCustkey() {
        return oCustkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_custkey
     *
     * @param oCustkey the value for orders.o_custkey
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoCustkey(Integer oCustkey) {
        this.oCustkey = oCustkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_orderstatus
     *
     * @return the value of orders.o_orderstatus
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public String getoOrderstatus() {
        return oOrderstatus;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_orderstatus
     *
     * @param oOrderstatus the value for orders.o_orderstatus
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoOrderstatus(String oOrderstatus) {
        this.oOrderstatus = oOrderstatus == null ? null : oOrderstatus.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_totalprice
     *
     * @return the value of orders.o_totalprice
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Double getoTotalprice() {
        return oTotalprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_totalprice
     *
     * @param oTotalprice the value for orders.o_totalprice
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoTotalprice(Double oTotalprice) {
        this.oTotalprice = oTotalprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_orderDATE
     *
     * @return the value of orders.o_orderDATE
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Date getoOrderdate() {
        return oOrderdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_orderDATE
     *
     * @param oOrderdate the value for orders.o_orderDATE
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoOrderdate(Date oOrderdate) {
        this.oOrderdate = oOrderdate;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_orderpriority
     *
     * @return the value of orders.o_orderpriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public String getoOrderpriority() {
        return oOrderpriority;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_orderpriority
     *
     * @param oOrderpriority the value for orders.o_orderpriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoOrderpriority(String oOrderpriority) {
        this.oOrderpriority = oOrderpriority == null ? null : oOrderpriority.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_clerk
     *
     * @return the value of orders.o_clerk
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public String getoClerk() {
        return oClerk;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_clerk
     *
     * @param oClerk the value for orders.o_clerk
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoClerk(String oClerk) {
        this.oClerk = oClerk == null ? null : oClerk.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_shippriority
     *
     * @return the value of orders.o_shippriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Integer getoShippriority() {
        return oShippriority;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_shippriority
     *
     * @param oShippriority the value for orders.o_shippriority
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoShippriority(Integer oShippriority) {
        this.oShippriority = oShippriority;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column orders.o_comment
     *
     * @return the value of orders.o_comment
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public String getoComment() {
        return oComment;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column orders.o_comment
     *
     * @param oComment the value for orders.o_comment
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setoComment(String oComment) {
        this.oComment = oComment == null ? null : oComment.trim();
    }
}