package com.demo.common.service.mysql.dal.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrdersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public OrdersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOOrderkeyIsNull() {
            addCriterion("o_orderkey is null");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyIsNotNull() {
            addCriterion("o_orderkey is not null");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyEqualTo(Integer value) {
            addCriterion("o_orderkey =", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyNotEqualTo(Integer value) {
            addCriterion("o_orderkey <>", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyGreaterThan(Integer value) {
            addCriterion("o_orderkey >", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_orderkey >=", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyLessThan(Integer value) {
            addCriterion("o_orderkey <", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyLessThanOrEqualTo(Integer value) {
            addCriterion("o_orderkey <=", value, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyIn(List<Integer> values) {
            addCriterion("o_orderkey in", values, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyNotIn(List<Integer> values) {
            addCriterion("o_orderkey not in", values, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyBetween(Integer value1, Integer value2) {
            addCriterion("o_orderkey between", value1, value2, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOOrderkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("o_orderkey not between", value1, value2, "oOrderkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyIsNull() {
            addCriterion("o_custkey is null");
            return (Criteria) this;
        }

        public Criteria andOCustkeyIsNotNull() {
            addCriterion("o_custkey is not null");
            return (Criteria) this;
        }

        public Criteria andOCustkeyEqualTo(Integer value) {
            addCriterion("o_custkey =", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyNotEqualTo(Integer value) {
            addCriterion("o_custkey <>", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyGreaterThan(Integer value) {
            addCriterion("o_custkey >", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_custkey >=", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyLessThan(Integer value) {
            addCriterion("o_custkey <", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyLessThanOrEqualTo(Integer value) {
            addCriterion("o_custkey <=", value, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyIn(List<Integer> values) {
            addCriterion("o_custkey in", values, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyNotIn(List<Integer> values) {
            addCriterion("o_custkey not in", values, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyBetween(Integer value1, Integer value2) {
            addCriterion("o_custkey between", value1, value2, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOCustkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("o_custkey not between", value1, value2, "oCustkey");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusIsNull() {
            addCriterion("o_orderstatus is null");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusIsNotNull() {
            addCriterion("o_orderstatus is not null");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusEqualTo(String value) {
            addCriterion("o_orderstatus =", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusNotEqualTo(String value) {
            addCriterion("o_orderstatus <>", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusGreaterThan(String value) {
            addCriterion("o_orderstatus >", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusGreaterThanOrEqualTo(String value) {
            addCriterion("o_orderstatus >=", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusLessThan(String value) {
            addCriterion("o_orderstatus <", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusLessThanOrEqualTo(String value) {
            addCriterion("o_orderstatus <=", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusLike(String value) {
            addCriterion("o_orderstatus like", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusNotLike(String value) {
            addCriterion("o_orderstatus not like", value, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusIn(List<String> values) {
            addCriterion("o_orderstatus in", values, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusNotIn(List<String> values) {
            addCriterion("o_orderstatus not in", values, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusBetween(String value1, String value2) {
            addCriterion("o_orderstatus between", value1, value2, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOOrderstatusNotBetween(String value1, String value2) {
            addCriterion("o_orderstatus not between", value1, value2, "oOrderstatus");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceIsNull() {
            addCriterion("o_totalprice is null");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceIsNotNull() {
            addCriterion("o_totalprice is not null");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceEqualTo(Double value) {
            addCriterion("o_totalprice =", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceNotEqualTo(Double value) {
            addCriterion("o_totalprice <>", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceGreaterThan(Double value) {
            addCriterion("o_totalprice >", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("o_totalprice >=", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceLessThan(Double value) {
            addCriterion("o_totalprice <", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceLessThanOrEqualTo(Double value) {
            addCriterion("o_totalprice <=", value, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceIn(List<Double> values) {
            addCriterion("o_totalprice in", values, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceNotIn(List<Double> values) {
            addCriterion("o_totalprice not in", values, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceBetween(Double value1, Double value2) {
            addCriterion("o_totalprice between", value1, value2, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOTotalpriceNotBetween(Double value1, Double value2) {
            addCriterion("o_totalprice not between", value1, value2, "oTotalprice");
            return (Criteria) this;
        }

        public Criteria andOOrderdateIsNull() {
            addCriterion("o_orderDATE is null");
            return (Criteria) this;
        }

        public Criteria andOOrderdateIsNotNull() {
            addCriterion("o_orderDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOOrderdateEqualTo(Date value) {
            addCriterionForJDBCDate("o_orderDATE =", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("o_orderDATE <>", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateGreaterThan(Date value) {
            addCriterionForJDBCDate("o_orderDATE >", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("o_orderDATE >=", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateLessThan(Date value) {
            addCriterionForJDBCDate("o_orderDATE <", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("o_orderDATE <=", value, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateIn(List<Date> values) {
            addCriterionForJDBCDate("o_orderDATE in", values, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("o_orderDATE not in", values, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("o_orderDATE between", value1, value2, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("o_orderDATE not between", value1, value2, "oOrderdate");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityIsNull() {
            addCriterion("o_orderpriority is null");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityIsNotNull() {
            addCriterion("o_orderpriority is not null");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityEqualTo(String value) {
            addCriterion("o_orderpriority =", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityNotEqualTo(String value) {
            addCriterion("o_orderpriority <>", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityGreaterThan(String value) {
            addCriterion("o_orderpriority >", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityGreaterThanOrEqualTo(String value) {
            addCriterion("o_orderpriority >=", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityLessThan(String value) {
            addCriterion("o_orderpriority <", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityLessThanOrEqualTo(String value) {
            addCriterion("o_orderpriority <=", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityLike(String value) {
            addCriterion("o_orderpriority like", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityNotLike(String value) {
            addCriterion("o_orderpriority not like", value, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityIn(List<String> values) {
            addCriterion("o_orderpriority in", values, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityNotIn(List<String> values) {
            addCriterion("o_orderpriority not in", values, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityBetween(String value1, String value2) {
            addCriterion("o_orderpriority between", value1, value2, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOOrderpriorityNotBetween(String value1, String value2) {
            addCriterion("o_orderpriority not between", value1, value2, "oOrderpriority");
            return (Criteria) this;
        }

        public Criteria andOClerkIsNull() {
            addCriterion("o_clerk is null");
            return (Criteria) this;
        }

        public Criteria andOClerkIsNotNull() {
            addCriterion("o_clerk is not null");
            return (Criteria) this;
        }

        public Criteria andOClerkEqualTo(String value) {
            addCriterion("o_clerk =", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkNotEqualTo(String value) {
            addCriterion("o_clerk <>", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkGreaterThan(String value) {
            addCriterion("o_clerk >", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkGreaterThanOrEqualTo(String value) {
            addCriterion("o_clerk >=", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkLessThan(String value) {
            addCriterion("o_clerk <", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkLessThanOrEqualTo(String value) {
            addCriterion("o_clerk <=", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkLike(String value) {
            addCriterion("o_clerk like", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkNotLike(String value) {
            addCriterion("o_clerk not like", value, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkIn(List<String> values) {
            addCriterion("o_clerk in", values, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkNotIn(List<String> values) {
            addCriterion("o_clerk not in", values, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkBetween(String value1, String value2) {
            addCriterion("o_clerk between", value1, value2, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOClerkNotBetween(String value1, String value2) {
            addCriterion("o_clerk not between", value1, value2, "oClerk");
            return (Criteria) this;
        }

        public Criteria andOShippriorityIsNull() {
            addCriterion("o_shippriority is null");
            return (Criteria) this;
        }

        public Criteria andOShippriorityIsNotNull() {
            addCriterion("o_shippriority is not null");
            return (Criteria) this;
        }

        public Criteria andOShippriorityEqualTo(Integer value) {
            addCriterion("o_shippriority =", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityNotEqualTo(Integer value) {
            addCriterion("o_shippriority <>", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityGreaterThan(Integer value) {
            addCriterion("o_shippriority >", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityGreaterThanOrEqualTo(Integer value) {
            addCriterion("o_shippriority >=", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityLessThan(Integer value) {
            addCriterion("o_shippriority <", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityLessThanOrEqualTo(Integer value) {
            addCriterion("o_shippriority <=", value, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityIn(List<Integer> values) {
            addCriterion("o_shippriority in", values, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityNotIn(List<Integer> values) {
            addCriterion("o_shippriority not in", values, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityBetween(Integer value1, Integer value2) {
            addCriterion("o_shippriority between", value1, value2, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOShippriorityNotBetween(Integer value1, Integer value2) {
            addCriterion("o_shippriority not between", value1, value2, "oShippriority");
            return (Criteria) this;
        }

        public Criteria andOCommentIsNull() {
            addCriterion("o_comment is null");
            return (Criteria) this;
        }

        public Criteria andOCommentIsNotNull() {
            addCriterion("o_comment is not null");
            return (Criteria) this;
        }

        public Criteria andOCommentEqualTo(String value) {
            addCriterion("o_comment =", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentNotEqualTo(String value) {
            addCriterion("o_comment <>", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentGreaterThan(String value) {
            addCriterion("o_comment >", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentGreaterThanOrEqualTo(String value) {
            addCriterion("o_comment >=", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentLessThan(String value) {
            addCriterion("o_comment <", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentLessThanOrEqualTo(String value) {
            addCriterion("o_comment <=", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentLike(String value) {
            addCriterion("o_comment like", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentNotLike(String value) {
            addCriterion("o_comment not like", value, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentIn(List<String> values) {
            addCriterion("o_comment in", values, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentNotIn(List<String> values) {
            addCriterion("o_comment not in", values, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentBetween(String value1, String value2) {
            addCriterion("o_comment between", value1, value2, "oComment");
            return (Criteria) this;
        }

        public Criteria andOCommentNotBetween(String value1, String value2) {
            addCriterion("o_comment not between", value1, value2, "oComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:33:40 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orders
     *
     * @mbggenerated Fri Jun 14 14:33:40 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}