package com.demo.common.service.mysql.dal.model;

public class Partsupp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partsupp.ps_partkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    private Integer psPartkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partsupp.ps_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    private Integer psSuppkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partsupp.ps_availqty
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    private Integer psAvailqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partsupp.ps_supplycost
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    private Double psSupplycost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partsupp.ps_comment
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    private String psComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partsupp.ps_partkey
     *
     * @return the value of partsupp.ps_partkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Integer getPsPartkey() {
        return psPartkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partsupp.ps_partkey
     *
     * @param psPartkey the value for partsupp.ps_partkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setPsPartkey(Integer psPartkey) {
        this.psPartkey = psPartkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partsupp.ps_suppkey
     *
     * @return the value of partsupp.ps_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Integer getPsSuppkey() {
        return psSuppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partsupp.ps_suppkey
     *
     * @param psSuppkey the value for partsupp.ps_suppkey
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setPsSuppkey(Integer psSuppkey) {
        this.psSuppkey = psSuppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partsupp.ps_availqty
     *
     * @return the value of partsupp.ps_availqty
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Integer getPsAvailqty() {
        return psAvailqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partsupp.ps_availqty
     *
     * @param psAvailqty the value for partsupp.ps_availqty
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setPsAvailqty(Integer psAvailqty) {
        this.psAvailqty = psAvailqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partsupp.ps_supplycost
     *
     * @return the value of partsupp.ps_supplycost
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public Double getPsSupplycost() {
        return psSupplycost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partsupp.ps_supplycost
     *
     * @param psSupplycost the value for partsupp.ps_supplycost
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setPsSupplycost(Double psSupplycost) {
        this.psSupplycost = psSupplycost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partsupp.ps_comment
     *
     * @return the value of partsupp.ps_comment
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public String getPsComment() {
        return psComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partsupp.ps_comment
     *
     * @param psComment the value for partsupp.ps_comment
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    public void setPsComment(String psComment) {
        this.psComment = psComment == null ? null : psComment.trim();
    }
}