package com.demo.common.service.mysql.dal.model;

public class Part {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_partkey
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private Integer pPartkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_name
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_mfgr
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pMfgr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_brand
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_type
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_size
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private Integer pSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_container
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pContainer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_retailprice
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private Double pRetailprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column part.p_comment
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    private String pComment;

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_partkey
     *
     * @return the value of part.p_partkey
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public Integer getpPartkey() {
        return pPartkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_partkey
     *
     * @param pPartkey the value for part.p_partkey
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpPartkey(Integer pPartkey) {
        this.pPartkey = pPartkey;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_name
     *
     * @return the value of part.p_name
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_name
     *
     * @param pName the value for part.p_name
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_mfgr
     *
     * @return the value of part.p_mfgr
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpMfgr() {
        return pMfgr;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_mfgr
     *
     * @param pMfgr the value for part.p_mfgr
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpMfgr(String pMfgr) {
        this.pMfgr = pMfgr == null ? null : pMfgr.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_brand
     *
     * @return the value of part.p_brand
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpBrand() {
        return pBrand;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_brand
     *
     * @param pBrand the value for part.p_brand
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpBrand(String pBrand) {
        this.pBrand = pBrand == null ? null : pBrand.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_type
     *
     * @return the value of part.p_type
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpType() {
        return pType;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_type
     *
     * @param pType the value for part.p_type
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpType(String pType) {
        this.pType = pType == null ? null : pType.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_size
     *
     * @return the value of part.p_size
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public Integer getpSize() {
        return pSize;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_size
     *
     * @param pSize the value for part.p_size
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpSize(Integer pSize) {
        this.pSize = pSize;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_container
     *
     * @return the value of part.p_container
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpContainer() {
        return pContainer;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_container
     *
     * @param pContainer the value for part.p_container
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpContainer(String pContainer) {
        this.pContainer = pContainer == null ? null : pContainer.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_retailprice
     *
     * @return the value of part.p_retailprice
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public Double getpRetailprice() {
        return pRetailprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_retailprice
     *
     * @param pRetailprice the value for part.p_retailprice
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpRetailprice(Double pRetailprice) {
        this.pRetailprice = pRetailprice;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column part.p_comment
     *
     * @return the value of part.p_comment
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getpComment() {
        return pComment;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column part.p_comment
     *
     * @param pComment the value for part.p_comment
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setpComment(String pComment) {
        this.pComment = pComment == null ? null : pComment.trim();
    }
}