package com.demo.common.service.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class PartExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public PartExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPPartkeyIsNull() {
            addCriterion("p_partkey is null");
            return (Criteria) this;
        }

        public Criteria andPPartkeyIsNotNull() {
            addCriterion("p_partkey is not null");
            return (Criteria) this;
        }

        public Criteria andPPartkeyEqualTo(Integer value) {
            addCriterion("p_partkey =", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyNotEqualTo(Integer value) {
            addCriterion("p_partkey <>", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyGreaterThan(Integer value) {
            addCriterion("p_partkey >", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_partkey >=", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyLessThan(Integer value) {
            addCriterion("p_partkey <", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyLessThanOrEqualTo(Integer value) {
            addCriterion("p_partkey <=", value, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyIn(List<Integer> values) {
            addCriterion("p_partkey in", values, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyNotIn(List<Integer> values) {
            addCriterion("p_partkey not in", values, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyBetween(Integer value1, Integer value2) {
            addCriterion("p_partkey between", value1, value2, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPPartkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("p_partkey not between", value1, value2, "pPartkey");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("p_name =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("p_name >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("p_name <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("p_name like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("p_name not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("p_name in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPMfgrIsNull() {
            addCriterion("p_mfgr is null");
            return (Criteria) this;
        }

        public Criteria andPMfgrIsNotNull() {
            addCriterion("p_mfgr is not null");
            return (Criteria) this;
        }

        public Criteria andPMfgrEqualTo(String value) {
            addCriterion("p_mfgr =", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrNotEqualTo(String value) {
            addCriterion("p_mfgr <>", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrGreaterThan(String value) {
            addCriterion("p_mfgr >", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrGreaterThanOrEqualTo(String value) {
            addCriterion("p_mfgr >=", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrLessThan(String value) {
            addCriterion("p_mfgr <", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrLessThanOrEqualTo(String value) {
            addCriterion("p_mfgr <=", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrLike(String value) {
            addCriterion("p_mfgr like", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrNotLike(String value) {
            addCriterion("p_mfgr not like", value, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrIn(List<String> values) {
            addCriterion("p_mfgr in", values, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrNotIn(List<String> values) {
            addCriterion("p_mfgr not in", values, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrBetween(String value1, String value2) {
            addCriterion("p_mfgr between", value1, value2, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPMfgrNotBetween(String value1, String value2) {
            addCriterion("p_mfgr not between", value1, value2, "pMfgr");
            return (Criteria) this;
        }

        public Criteria andPBrandIsNull() {
            addCriterion("p_brand is null");
            return (Criteria) this;
        }

        public Criteria andPBrandIsNotNull() {
            addCriterion("p_brand is not null");
            return (Criteria) this;
        }

        public Criteria andPBrandEqualTo(String value) {
            addCriterion("p_brand =", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandNotEqualTo(String value) {
            addCriterion("p_brand <>", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandGreaterThan(String value) {
            addCriterion("p_brand >", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandGreaterThanOrEqualTo(String value) {
            addCriterion("p_brand >=", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandLessThan(String value) {
            addCriterion("p_brand <", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandLessThanOrEqualTo(String value) {
            addCriterion("p_brand <=", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandLike(String value) {
            addCriterion("p_brand like", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandNotLike(String value) {
            addCriterion("p_brand not like", value, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandIn(List<String> values) {
            addCriterion("p_brand in", values, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandNotIn(List<String> values) {
            addCriterion("p_brand not in", values, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandBetween(String value1, String value2) {
            addCriterion("p_brand between", value1, value2, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPBrandNotBetween(String value1, String value2) {
            addCriterion("p_brand not between", value1, value2, "pBrand");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNull() {
            addCriterion("p_type is null");
            return (Criteria) this;
        }

        public Criteria andPTypeIsNotNull() {
            addCriterion("p_type is not null");
            return (Criteria) this;
        }

        public Criteria andPTypeEqualTo(String value) {
            addCriterion("p_type =", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotEqualTo(String value) {
            addCriterion("p_type <>", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThan(String value) {
            addCriterion("p_type >", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeGreaterThanOrEqualTo(String value) {
            addCriterion("p_type >=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThan(String value) {
            addCriterion("p_type <", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLessThanOrEqualTo(String value) {
            addCriterion("p_type <=", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeLike(String value) {
            addCriterion("p_type like", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotLike(String value) {
            addCriterion("p_type not like", value, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeIn(List<String> values) {
            addCriterion("p_type in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotIn(List<String> values) {
            addCriterion("p_type not in", values, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeBetween(String value1, String value2) {
            addCriterion("p_type between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPTypeNotBetween(String value1, String value2) {
            addCriterion("p_type not between", value1, value2, "pType");
            return (Criteria) this;
        }

        public Criteria andPSizeIsNull() {
            addCriterion("p_size is null");
            return (Criteria) this;
        }

        public Criteria andPSizeIsNotNull() {
            addCriterion("p_size is not null");
            return (Criteria) this;
        }

        public Criteria andPSizeEqualTo(Integer value) {
            addCriterion("p_size =", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeNotEqualTo(Integer value) {
            addCriterion("p_size <>", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeGreaterThan(Integer value) {
            addCriterion("p_size >", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_size >=", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeLessThan(Integer value) {
            addCriterion("p_size <", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeLessThanOrEqualTo(Integer value) {
            addCriterion("p_size <=", value, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeIn(List<Integer> values) {
            addCriterion("p_size in", values, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeNotIn(List<Integer> values) {
            addCriterion("p_size not in", values, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeBetween(Integer value1, Integer value2) {
            addCriterion("p_size between", value1, value2, "pSize");
            return (Criteria) this;
        }

        public Criteria andPSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("p_size not between", value1, value2, "pSize");
            return (Criteria) this;
        }

        public Criteria andPContainerIsNull() {
            addCriterion("p_container is null");
            return (Criteria) this;
        }

        public Criteria andPContainerIsNotNull() {
            addCriterion("p_container is not null");
            return (Criteria) this;
        }

        public Criteria andPContainerEqualTo(String value) {
            addCriterion("p_container =", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerNotEqualTo(String value) {
            addCriterion("p_container <>", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerGreaterThan(String value) {
            addCriterion("p_container >", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerGreaterThanOrEqualTo(String value) {
            addCriterion("p_container >=", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerLessThan(String value) {
            addCriterion("p_container <", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerLessThanOrEqualTo(String value) {
            addCriterion("p_container <=", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerLike(String value) {
            addCriterion("p_container like", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerNotLike(String value) {
            addCriterion("p_container not like", value, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerIn(List<String> values) {
            addCriterion("p_container in", values, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerNotIn(List<String> values) {
            addCriterion("p_container not in", values, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerBetween(String value1, String value2) {
            addCriterion("p_container between", value1, value2, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPContainerNotBetween(String value1, String value2) {
            addCriterion("p_container not between", value1, value2, "pContainer");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceIsNull() {
            addCriterion("p_retailprice is null");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceIsNotNull() {
            addCriterion("p_retailprice is not null");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceEqualTo(Double value) {
            addCriterion("p_retailprice =", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceNotEqualTo(Double value) {
            addCriterion("p_retailprice <>", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceGreaterThan(Double value) {
            addCriterion("p_retailprice >", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceGreaterThanOrEqualTo(Double value) {
            addCriterion("p_retailprice >=", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceLessThan(Double value) {
            addCriterion("p_retailprice <", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceLessThanOrEqualTo(Double value) {
            addCriterion("p_retailprice <=", value, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceIn(List<Double> values) {
            addCriterion("p_retailprice in", values, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceNotIn(List<Double> values) {
            addCriterion("p_retailprice not in", values, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceBetween(Double value1, Double value2) {
            addCriterion("p_retailprice between", value1, value2, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPRetailpriceNotBetween(Double value1, Double value2) {
            addCriterion("p_retailprice not between", value1, value2, "pRetailprice");
            return (Criteria) this;
        }

        public Criteria andPCommentIsNull() {
            addCriterion("p_comment is null");
            return (Criteria) this;
        }

        public Criteria andPCommentIsNotNull() {
            addCriterion("p_comment is not null");
            return (Criteria) this;
        }

        public Criteria andPCommentEqualTo(String value) {
            addCriterion("p_comment =", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentNotEqualTo(String value) {
            addCriterion("p_comment <>", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentGreaterThan(String value) {
            addCriterion("p_comment >", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentGreaterThanOrEqualTo(String value) {
            addCriterion("p_comment >=", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentLessThan(String value) {
            addCriterion("p_comment <", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentLessThanOrEqualTo(String value) {
            addCriterion("p_comment <=", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentLike(String value) {
            addCriterion("p_comment like", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentNotLike(String value) {
            addCriterion("p_comment not like", value, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentIn(List<String> values) {
            addCriterion("p_comment in", values, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentNotIn(List<String> values) {
            addCriterion("p_comment not in", values, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentBetween(String value1, String value2) {
            addCriterion("p_comment between", value1, value2, "pComment");
            return (Criteria) this;
        }

        public Criteria andPCommentNotBetween(String value1, String value2) {
            addCriterion("p_comment not between", value1, value2, "pComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table part
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:33:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table part
     *
     * @mbggenerated Fri Jun 14 14:33:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}