package com.demo.common.service.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class RegionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public RegionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRRegionkeyIsNull() {
            addCriterion("r_regionkey is null");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyIsNotNull() {
            addCriterion("r_regionkey is not null");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyEqualTo(Integer value) {
            addCriterion("r_regionkey =", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyNotEqualTo(Integer value) {
            addCriterion("r_regionkey <>", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyGreaterThan(Integer value) {
            addCriterion("r_regionkey >", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("r_regionkey >=", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyLessThan(Integer value) {
            addCriterion("r_regionkey <", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyLessThanOrEqualTo(Integer value) {
            addCriterion("r_regionkey <=", value, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyIn(List<Integer> values) {
            addCriterion("r_regionkey in", values, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyNotIn(List<Integer> values) {
            addCriterion("r_regionkey not in", values, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyBetween(Integer value1, Integer value2) {
            addCriterion("r_regionkey between", value1, value2, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRRegionkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("r_regionkey not between", value1, value2, "rRegionkey");
            return (Criteria) this;
        }

        public Criteria andRNameIsNull() {
            addCriterion("r_name is null");
            return (Criteria) this;
        }

        public Criteria andRNameIsNotNull() {
            addCriterion("r_name is not null");
            return (Criteria) this;
        }

        public Criteria andRNameEqualTo(String value) {
            addCriterion("r_name =", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotEqualTo(String value) {
            addCriterion("r_name <>", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThan(String value) {
            addCriterion("r_name >", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameGreaterThanOrEqualTo(String value) {
            addCriterion("r_name >=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThan(String value) {
            addCriterion("r_name <", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLessThanOrEqualTo(String value) {
            addCriterion("r_name <=", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameLike(String value) {
            addCriterion("r_name like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotLike(String value) {
            addCriterion("r_name not like", value, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameIn(List<String> values) {
            addCriterion("r_name in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotIn(List<String> values) {
            addCriterion("r_name not in", values, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameBetween(String value1, String value2) {
            addCriterion("r_name between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRNameNotBetween(String value1, String value2) {
            addCriterion("r_name not between", value1, value2, "rName");
            return (Criteria) this;
        }

        public Criteria andRCommentIsNull() {
            addCriterion("r_comment is null");
            return (Criteria) this;
        }

        public Criteria andRCommentIsNotNull() {
            addCriterion("r_comment is not null");
            return (Criteria) this;
        }

        public Criteria andRCommentEqualTo(String value) {
            addCriterion("r_comment =", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentNotEqualTo(String value) {
            addCriterion("r_comment <>", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentGreaterThan(String value) {
            addCriterion("r_comment >", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentGreaterThanOrEqualTo(String value) {
            addCriterion("r_comment >=", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentLessThan(String value) {
            addCriterion("r_comment <", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentLessThanOrEqualTo(String value) {
            addCriterion("r_comment <=", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentLike(String value) {
            addCriterion("r_comment like", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentNotLike(String value) {
            addCriterion("r_comment not like", value, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentIn(List<String> values) {
            addCriterion("r_comment in", values, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentNotIn(List<String> values) {
            addCriterion("r_comment not in", values, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentBetween(String value1, String value2) {
            addCriterion("r_comment between", value1, value2, "rComment");
            return (Criteria) this;
        }

        public Criteria andRCommentNotBetween(String value1, String value2) {
            addCriterion("r_comment not between", value1, value2, "rComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table region
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:34:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}