package com.demo.common.service.mysql.dal.model;

import java.util.Date;

public class ShipperEntranceSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.request_type
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private String requestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.customer_id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.customer_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private Boolean unpickup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.site_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private Boolean siteUnpickup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.union_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private Boolean unionUnpickup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.user_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.crate_time
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private Date crateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mc_shipper_entrance_setting.status
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.id
     *
     * @return the value of mc_shipper_entrance_setting.id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.id
     *
     * @param id the value for mc_shipper_entrance_setting.id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.request_type
     *
     * @return the value of mc_shipper_entrance_setting.request_type
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public String getRequestType() {
        return requestType;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.request_type
     *
     * @param requestType the value for mc_shipper_entrance_setting.request_type
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setRequestType(String requestType) {
        this.requestType = requestType == null ? null : requestType.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.customer_id
     *
     * @return the value of mc_shipper_entrance_setting.customer_id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.customer_id
     *
     * @param customerId the value for mc_shipper_entrance_setting.customer_id
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.customer_name
     *
     * @return the value of mc_shipper_entrance_setting.customer_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.customer_name
     *
     * @param customerName the value for mc_shipper_entrance_setting.customer_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.unpickup
     *
     * @return the value of mc_shipper_entrance_setting.unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public Boolean getUnpickup() {
        return unpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.unpickup
     *
     * @param unpickup the value for mc_shipper_entrance_setting.unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setUnpickup(Boolean unpickup) {
        this.unpickup = unpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.site_unpickup
     *
     * @return the value of mc_shipper_entrance_setting.site_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public Boolean getSiteUnpickup() {
        return siteUnpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.site_unpickup
     *
     * @param siteUnpickup the value for mc_shipper_entrance_setting.site_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setSiteUnpickup(Boolean siteUnpickup) {
        this.siteUnpickup = siteUnpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.union_unpickup
     *
     * @return the value of mc_shipper_entrance_setting.union_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public Boolean getUnionUnpickup() {
        return unionUnpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.union_unpickup
     *
     * @param unionUnpickup the value for mc_shipper_entrance_setting.union_unpickup
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setUnionUnpickup(Boolean unionUnpickup) {
        this.unionUnpickup = unionUnpickup;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.user_name
     *
     * @return the value of mc_shipper_entrance_setting.user_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.user_name
     *
     * @param userName the value for mc_shipper_entrance_setting.user_name
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.crate_time
     *
     * @return the value of mc_shipper_entrance_setting.crate_time
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public Date getCrateTime() {
        return crateTime;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.crate_time
     *
     * @param crateTime the value for mc_shipper_entrance_setting.crate_time
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setCrateTime(Date crateTime) {
        this.crateTime = crateTime;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method returns the value of the database column mc_shipper_entrance_setting.status
     *
     * @return the value of mc_shipper_entrance_setting.status
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method sets the value of the database column mc_shipper_entrance_setting.status
     *
     * @param status the value for mc_shipper_entrance_setting.status
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}