package com.demo.common.service.mysql.dal.model;

import java.util.ArrayList;
import java.util.List;

public class SupplierExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public SupplierExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSSuppkeyIsNull() {
            addCriterion("s_suppkey is null");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyIsNotNull() {
            addCriterion("s_suppkey is not null");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyEqualTo(Integer value) {
            addCriterion("s_suppkey =", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyNotEqualTo(Integer value) {
            addCriterion("s_suppkey <>", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyGreaterThan(Integer value) {
            addCriterion("s_suppkey >", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_suppkey >=", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyLessThan(Integer value) {
            addCriterion("s_suppkey <", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyLessThanOrEqualTo(Integer value) {
            addCriterion("s_suppkey <=", value, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyIn(List<Integer> values) {
            addCriterion("s_suppkey in", values, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyNotIn(List<Integer> values) {
            addCriterion("s_suppkey not in", values, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyBetween(Integer value1, Integer value2) {
            addCriterion("s_suppkey between", value1, value2, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSSuppkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("s_suppkey not between", value1, value2, "sSuppkey");
            return (Criteria) this;
        }

        public Criteria andSNameIsNull() {
            addCriterion("s_name is null");
            return (Criteria) this;
        }

        public Criteria andSNameIsNotNull() {
            addCriterion("s_name is not null");
            return (Criteria) this;
        }

        public Criteria andSNameEqualTo(String value) {
            addCriterion("s_name =", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotEqualTo(String value) {
            addCriterion("s_name <>", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThan(String value) {
            addCriterion("s_name >", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameGreaterThanOrEqualTo(String value) {
            addCriterion("s_name >=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThan(String value) {
            addCriterion("s_name <", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLessThanOrEqualTo(String value) {
            addCriterion("s_name <=", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameLike(String value) {
            addCriterion("s_name like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotLike(String value) {
            addCriterion("s_name not like", value, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameIn(List<String> values) {
            addCriterion("s_name in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotIn(List<String> values) {
            addCriterion("s_name not in", values, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameBetween(String value1, String value2) {
            addCriterion("s_name between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSNameNotBetween(String value1, String value2) {
            addCriterion("s_name not between", value1, value2, "sName");
            return (Criteria) this;
        }

        public Criteria andSAddressIsNull() {
            addCriterion("s_address is null");
            return (Criteria) this;
        }

        public Criteria andSAddressIsNotNull() {
            addCriterion("s_address is not null");
            return (Criteria) this;
        }

        public Criteria andSAddressEqualTo(String value) {
            addCriterion("s_address =", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotEqualTo(String value) {
            addCriterion("s_address <>", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressGreaterThan(String value) {
            addCriterion("s_address >", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressGreaterThanOrEqualTo(String value) {
            addCriterion("s_address >=", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLessThan(String value) {
            addCriterion("s_address <", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLessThanOrEqualTo(String value) {
            addCriterion("s_address <=", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressLike(String value) {
            addCriterion("s_address like", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotLike(String value) {
            addCriterion("s_address not like", value, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressIn(List<String> values) {
            addCriterion("s_address in", values, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotIn(List<String> values) {
            addCriterion("s_address not in", values, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressBetween(String value1, String value2) {
            addCriterion("s_address between", value1, value2, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSAddressNotBetween(String value1, String value2) {
            addCriterion("s_address not between", value1, value2, "sAddress");
            return (Criteria) this;
        }

        public Criteria andSNationkeyIsNull() {
            addCriterion("s_nationkey is null");
            return (Criteria) this;
        }

        public Criteria andSNationkeyIsNotNull() {
            addCriterion("s_nationkey is not null");
            return (Criteria) this;
        }

        public Criteria andSNationkeyEqualTo(Integer value) {
            addCriterion("s_nationkey =", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyNotEqualTo(Integer value) {
            addCriterion("s_nationkey <>", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyGreaterThan(Integer value) {
            addCriterion("s_nationkey >", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_nationkey >=", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyLessThan(Integer value) {
            addCriterion("s_nationkey <", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyLessThanOrEqualTo(Integer value) {
            addCriterion("s_nationkey <=", value, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyIn(List<Integer> values) {
            addCriterion("s_nationkey in", values, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyNotIn(List<Integer> values) {
            addCriterion("s_nationkey not in", values, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyBetween(Integer value1, Integer value2) {
            addCriterion("s_nationkey between", value1, value2, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSNationkeyNotBetween(Integer value1, Integer value2) {
            addCriterion("s_nationkey not between", value1, value2, "sNationkey");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNull() {
            addCriterion("s_phone is null");
            return (Criteria) this;
        }

        public Criteria andSPhoneIsNotNull() {
            addCriterion("s_phone is not null");
            return (Criteria) this;
        }

        public Criteria andSPhoneEqualTo(String value) {
            addCriterion("s_phone =", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotEqualTo(String value) {
            addCriterion("s_phone <>", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThan(String value) {
            addCriterion("s_phone >", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("s_phone >=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThan(String value) {
            addCriterion("s_phone <", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLessThanOrEqualTo(String value) {
            addCriterion("s_phone <=", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneLike(String value) {
            addCriterion("s_phone like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotLike(String value) {
            addCriterion("s_phone not like", value, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneIn(List<String> values) {
            addCriterion("s_phone in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotIn(List<String> values) {
            addCriterion("s_phone not in", values, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneBetween(String value1, String value2) {
            addCriterion("s_phone between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSPhoneNotBetween(String value1, String value2) {
            addCriterion("s_phone not between", value1, value2, "sPhone");
            return (Criteria) this;
        }

        public Criteria andSAcctbalIsNull() {
            addCriterion("s_acctbal is null");
            return (Criteria) this;
        }

        public Criteria andSAcctbalIsNotNull() {
            addCriterion("s_acctbal is not null");
            return (Criteria) this;
        }

        public Criteria andSAcctbalEqualTo(Double value) {
            addCriterion("s_acctbal =", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalNotEqualTo(Double value) {
            addCriterion("s_acctbal <>", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalGreaterThan(Double value) {
            addCriterion("s_acctbal >", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalGreaterThanOrEqualTo(Double value) {
            addCriterion("s_acctbal >=", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalLessThan(Double value) {
            addCriterion("s_acctbal <", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalLessThanOrEqualTo(Double value) {
            addCriterion("s_acctbal <=", value, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalIn(List<Double> values) {
            addCriterion("s_acctbal in", values, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalNotIn(List<Double> values) {
            addCriterion("s_acctbal not in", values, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalBetween(Double value1, Double value2) {
            addCriterion("s_acctbal between", value1, value2, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSAcctbalNotBetween(Double value1, Double value2) {
            addCriterion("s_acctbal not between", value1, value2, "sAcctbal");
            return (Criteria) this;
        }

        public Criteria andSCommentIsNull() {
            addCriterion("s_comment is null");
            return (Criteria) this;
        }

        public Criteria andSCommentIsNotNull() {
            addCriterion("s_comment is not null");
            return (Criteria) this;
        }

        public Criteria andSCommentEqualTo(String value) {
            addCriterion("s_comment =", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentNotEqualTo(String value) {
            addCriterion("s_comment <>", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentGreaterThan(String value) {
            addCriterion("s_comment >", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentGreaterThanOrEqualTo(String value) {
            addCriterion("s_comment >=", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentLessThan(String value) {
            addCriterion("s_comment <", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentLessThanOrEqualTo(String value) {
            addCriterion("s_comment <=", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentLike(String value) {
            addCriterion("s_comment like", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentNotLike(String value) {
            addCriterion("s_comment not like", value, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentIn(List<String> values) {
            addCriterion("s_comment in", values, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentNotIn(List<String> values) {
            addCriterion("s_comment not in", values, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentBetween(String value1, String value2) {
            addCriterion("s_comment between", value1, value2, "sComment");
            return (Criteria) this;
        }

        public Criteria andSCommentNotBetween(String value1, String value2) {
            addCriterion("s_comment not between", value1, value2, "sComment");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 14 14:34:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}