server:
  port: 8091

spring:
  profiles:
    active: ${profiles.active}
  application:
    name: spring-cloud-client02
  zipkin:
    base-url: http://localhost:18093
  sleuth:
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
#    web:
#      client:
#        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    restart:
      enabled: true
    pause:
      enabled: true

# 开启feign-hystrix
feign:
  hystrix:
    enabled: true
#  compression:
#    request:
#      # 开启feign请求时的压缩， application client -> application service
#      enabled: true
#      # 设置可以压缩的请求/响应的类型。
#      mime-types: text/xml,application/xml,application/json
#      # 当请求的数据容量达到多少的时候，使用压缩。默认是2048字节。
#      min-request-size: 512
#    response:
#      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10  # 实例续约间隔时间
    lease-expiration-duration-in-seconds: 30 # 实例超时时间

  client:
    healthcheck:
      enabled: true # 开启健康检查
    service-url:
      defaultZone: http://localhost:18090/eureka

