server:
  port: 8082

spring:
  application:
    name: spring-cloud-feign01

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18090/eureka,http://localhost:18091/eureka

feign:
  hystrix:
    enabled: true
