package com.demo.common.service.mysql.dal.mapper;

import com.demo.common.service.mysql.dal.model.Supplier;
import com.demo.common.service.mysql.dal.model.SupplierExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplierMapper {
    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int countByExample(SupplierExample example);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int deleteByExample(SupplierExample example);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int insert(Supplier record);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int insertSelective(Supplier record);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    List<Supplier> selectByExample(SupplierExample example);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int updateByExampleSelective(@Param("record") Supplier record, @Param("example") SupplierExample example);

    /**
     * This method was generated by my.Batis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Fri Jun 14 14:34:35 CST 2019
     */
    int updateByExample(@Param("record") Supplier record, @Param("example") SupplierExample example);
}