server:
  port: 8078

spring:
  profiles:
    active: "@profiles.active@"

  kafka:
    producer:
      bootstrap-servers: 192.168.78.130:19092
      #      groupId: zj.hello-app
      retries: 0
      batch-size: 1024
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

dubbo:
  application:
    name: hello-world-app
    logger: log4j
  registry:
    address: zookeeper://192.168.78.130:12181
  protocol:
    name: dubbo
    port: 28081
  scan:
    base-packages: hello.service
  provider:
    group: zj.hello-world-app
    timeout: 5000
    protocol: dubbo
    retries: 3
    async: false
    accesslog: true
    proxy: javassist

#  redis:
#    sentinel:
#      master: logistics_01
#      nodes: 192.168.78.129:26379