spring:
  application:
    name: spring-cloud-service01
server:
  port: 8090
eureka:
  instance:
    hostname: localhost
  #    prefer-ip-address: true
  #    ip-address: 192.168.3.150
  #    instance-id: ${eureka.instance.ip-address}:${server.port}

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/