server:
  port: 8087

spring:
  application:
    name: spring-cloud-config-client01
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: spring-cloud-config-server01
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
#    username:
#    password:

# 刷新配置地址: http://localhost:8087/actuator/bus-refresh
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka,http://localhost:8091/eureka
