spring:
  application:
    name: spring-cloud-eureka01
  profiles:
    active: ${profiles.active}

#eureka:
#  instance:
#    non-secure-port-enabled: true //1 开启不安全通信的端口，就是使用http进行通信
#    non-secure-port: ${server.port:7001} //2 设置不安全端口号
#    secure-port-enabled: false //3 开启安全通信的端口，就是使用https进行通信
#    secure-port: 443 //4 设置安全通信的端口号
#
#    hostname: xuexuantest  //5  默认注册到服务中心，显示的名称是 hostname+appname+port
#    prefer-ip-address: true //6 使用ip地址来注册到服务中心，显示的是实例名称, true则hostname将失效
#    ip-address: 192.168.1.108 //7 设置访问服务的ip地址 因为需要通过外网来访问该服务，通常设置为公网ip
#    instance-id: ${eureka.instance.ip-address}:${server.port}  //8 设置 注册服务中心，显示的实例名称
#  client:
#    register-with-eureka: false  //9 是否注册自身到eureka服务器,当前这个应用就是eureka服务器所以设置false
#    fetch-registry: false    //10 是否从eureka服务器获取注册信息,当前这个应用就是eureka服务器所以设置false
#    service-url:         //11
#      defaultZone: http://192.168.1.108:${eureka.port:8888}/eureka/ //12 设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
