package com.kdniao.logisticsfront.common.biz.service.impl.mybatis.dal.mapper;

import com.kdniao.logisticsfront.common.biz.service.impl.mybatis.dal.model.ShipperEntranceSetting;
import com.kdniao.logisticsfront.common.biz.service.impl.mybatis.dal.model.ShipperEntranceSettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShipperEntranceSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    long countByExample(ShipperEntranceSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    int deleteByExample(ShipperEntranceSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    int insert(ShipperEntranceSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    int insertSelective(ShipperEntranceSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    List<ShipperEntranceSetting> selectByExample(ShipperEntranceSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShipperEntranceSetting record, @Param("example") ShipperEntranceSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mc_shipper_entrance_setting
     *
     * @mbg.generated Tue May 28 11:21:16 CST 2019
     */
    int updateByExample(@Param("record") ShipperEntranceSetting record, @Param("example") ShipperEntranceSettingExample example);
}