server:
  port: 8083

spring:
  profiles:
    active: ${profiles.active}
  application:
    name: spring-cloud-zuul01

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18090/eureka,http://localhost:18091/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-ribbon01
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-feign01
