server:
  port: 8079

spring:
  application:
    name: spring-cloud-zuul01

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka,http://localhost:8091/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-ribbon01
    api-b:
      path: /api-b/**
      serviceId: spring-cloud-feign01
