server:
  port: 18092

spring:
  profiles:
    active: ${profiles.active}
  application:
    name: spring-cloud-config-server01


  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zj2626/SpringcloudConfig/
          search-paths: respo
#          username: un
#          password: pw
#          basedir: D:/Config/basedir

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:18090/eureka,http://localhost:18091/eureka
