server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server01


  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zj2626/SpringcloudConfig/
          search-paths: respo
#          username: un
#          password: pw

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka,http://localhost:8091/eureka
