package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.mapper;

import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.Lineitem;
import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.LineitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LineitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int countByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int deleteByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int insert(Lineitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int insertSelective(Lineitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    List<Lineitem> selectByExample(LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Lineitem record, @Param("example") LineitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lineitem
     *
     * @mbggenerated Fri Jun 14 14:32:46 CST 2019
     */
    int updateByExample(@Param("record") Lineitem record, @Param("example") LineitemExample example);
}