package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.mapper;

import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.Partsupp;
import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.PartsuppExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PartsuppMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int countByExample(PartsuppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int deleteByExample(PartsuppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int insert(Partsupp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int insertSelective(Partsupp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    List<Partsupp> selectByExample(PartsuppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int updateByExampleSelective(@Param("record") Partsupp record, @Param("example") PartsuppExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partsupp
     *
     * @mbggenerated Fri Jun 14 14:34:05 CST 2019
     */
    int updateByExample(@Param("record") Partsupp record, @Param("example") PartsuppExample example);
}