package com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.mapper;

import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.Region;
import com.kdniao.logisticsfront.common.biz.service.impl.mysql.dal.model.RegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int countByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int deleteByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int insert(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int insertSelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    List<Region> selectByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Region record, @Param("example") RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbggenerated Fri Jun 14 14:34:21 CST 2019
     */
    int updateByExample(@Param("record") Region record, @Param("example") RegionExample example);
}