server:
  port: 18091

spring:
  application:
    name: spring-cloud-service02

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:18091/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
