server:
  port: 18091

spring:
  application:
    name: spring-cloud-service02

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:18090/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
